services:
  - type: web
    name: syncd-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: syncd-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
